packages:
  - "lib/*"
  - "examples/*"
catalog:
  "@babel/core": "7.28.5"
  "@playwright/test": "1.50.1"
  "@rollup/plugin-babel": "6.1.0"
  "@tailwindcss/vite": "4.1.17"
  "@testing-library/dom": "10.4.1"
  "@testing-library/jest-dom": "6.9.1"
  "@testing-library/react": "16.3.0"
  "@toolwind/anchors": "1.0.10"
  "@types/node": "^22.10.5"
  "@types/react": "19.2.5"
  "@types/react-dom": "19.2.3"
  "@typescript/native-preview": "7.0.0-dev.20260122.3"
  "@vitejs/plugin-react": "5.1.1"
  "babel-plugin-react-compiler": "1.0.0"
  "lit-html": "3.3.2"
  "oxfmt": "0.26.0"
  "oxlint": "1.41.0"
  "oxlint-tsgolint": "0.11.1"
  "react": "^19.2.0"
  "react-dom": "^19.2.0"
  "react-is": "19.2.0"
  "react-server-dom-webpack": "^19.1.0"
  "tailwindcss": "4.1.17"
  "tsdown": "0.20.1"
  "typescript": "5.9.3"
  "vite": "8.0.0-beta.0"
  "vitest": "4.0.9"
  "web-streams-polyfill": "^4.1.0"
