import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/http.ts",
    "src/response.ts",
    "src/router.ts",
    "src/types.ts",
    "src/worker.ts",
    "src/rsc/index.ts",
    "src/rsc/client-only.ts",
    "src/rsc/client-reference.ts",
    "src/rsc/client.ts",
    "src/rsc/flight-serializer.ts",
    "src/rsc/http.ts",
    "src/rsc/module-registry.ts",
    "src/rsc/polyfill.ts",
    "src/rsc/response.ts",
    "src/rsc/server.ts",
    "src/rsc/types.ts",
    "src/rsc/webpack-shim.ts",
  ],
  outDir: "dist",
  format: "esm",
  platform: "neutral",
  clean: true,
  unbundle: true,
  skipNodeModulesBundle: true,
  dts: false,
  external: [
    "react",
    "react-is",
    "react-server-dom-webpack",
    /^react-server-dom-webpack\/.+$/,
    "web-streams-polyfill",
    /^@lib\//,
  ],
  copy: [
    {
      from: "src/rsc/react-server-dom-webpack.d.ts",
      to: "dist/rsc",
    },
  ],
});
